apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-app
spec:
  project: default
  source:
    repoURL: https://github.com/ajithshah/argo-cd.git
    path: service/charts/service/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
